# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=999)),
                ('about_my_blog', models.CharField(max_length=999)),
                ('qq', models.CharField(max_length=999)),
                ('git', models.CharField(default='', max_length=999)),
                ('email', models.CharField(max_length=999)),
            ],
        ),
    ]
